README.md

The prometheus terraform modules have been imported from https://github.com/DFE-Digital/bat-platform-building-blocks , including the git history.
Root readme has been added.
Change the URL according to the readme

Import from bat-platform-building-blocks

---

alertmanager/config/alertmanager.yml.tmpl

When if/endif is not the beginning of the line, the alertmanager config
fails to evaluate the value of slack_api_url
Alertmanager crashes, with this in the logs
```
msg="Loading configuration file failed" file=alertmanager.yml err="yaml: line 3: mapping values are not allowed in this context"
```

Correct indentation of if/endif

---

grafana/config/plugins.txt

Adding the google Sheet Grafana plugin into available data sources, this will need a config, but working on that as another PR
It does allow for Manual Linking at this point 
https://grafana-dev-get-into-teaching.london.cloudapps.digital/d/SW1fFbsMk/new-dashboard-copy?editPanel=2&orgId=1

Update plugins.txt adding Google Sheets Data Source

---

grafana/config.tf
grafana/datasources/google-sheets.yml.tmpl
grafana/input.tf

[Trello Ticket](https://trello.com/c/mGbZZoMQ/1340-users-against-cpu-memory)
Enabled the passing in  a JWT secret, to the Grafana module. Which in turn permits the data source access to the sheets that have been shared to the SP
Instructions on how to create an JWT are at:  [JWT](https://dfedigital.atlassian.net/wiki/spaces/BaT/pages/2562424899/Google+Sheets+Data+Source)
Testing was at:  [Grafana](https://grafana-dev-get-into-teaching.london.cloudapps.digital/d/uhhddQsGk/test?orgId=1&from=1614569519883&to=1614591119883)

Added Google-Sheets-Configuration

---

influxdb/input.tf
influxdb/resources.tf
prometheus_all/input.tf
prometheus_all/resources.tf

Allow individual consumers to choose between `tiny` and `small` for InfluxDB.

Variable for InfluxDB service plan

---

grafana/README.md
grafana/config.tf
grafana/datasources/elasticsearch.yml.tmpl
grafana/input.tf

Adding a data source for Grafana, which will permit the access to an ELK stack via a URL, Primarily intended for accessing logit.io The call to Grafana will need URL/Username/Password
Tested deployment to [GiT Monitoring ](https://grafana-dev-get-into-teaching.london.cloudapps.digital/?orgId=1 )

EleasticSearch Datasource

---

grafana/dashboards/Postgres.json
prometheus/templates/prometheus.yml.tmpl

A simple Postgres dashboard based upon the limited data provided from the Government PaaS Exporter.
( This may no longer exist due to deployments ) [Dashboard](https://grafana-dev-get-into-teaching.london.cloudapps.digital/d/a2FR6FUMz/cf-databases?orgId=1&refresh=10s) Though it should be possible to manually import the json file

Simple Postgres Dashboard

---

prometheus_all/input.tf

If the prometheus_all parameter has a "" it overrides the defaults bellow. 
This means we need to ensure prometheus_all defaults are set to reasonable figures

default runtime version at highest level

---

alertmanager/config/slack.tmpl

Currently, when slack messages are sent to a channel, they are delivered quietly with no immediate attention or notification. This change is to include `@channel`, alongside the alert message annotation. So that, when messages are delivered, they come with Slack notification i.e. desktop notification.

[teva-2163] Add @channel mention to alertmanager's template

---

prometheus/input.tf
prometheus/resources.tf

Prometheus has been crashing because of high disk usage. We suspect it is because it stores metrics locally with a default retention of 15 days. Since we store metrics permanently in InfluxDB we can reduce it to 1 day.
Default options have been moved to input.tf for readability.
Deployed to https://grafana-bat-qa.london.cloudapps.digital

Reduce prometheus local disk storage

---

grafana/dashboards/paas_billing.json

Use last_over_time to fill gaps and sort values for clarity
Import to Grafana or view here: https://grafana-teaching-vacancies.london.cloudapps.digital/d/tIw8h_G7z2/paas-billing-new?orgId=1&refresh=1h

[272] PaaS billing dashboard tweaks

---

grafana/config.tf
grafana/input.tf
prometheus/input.tf
prometheus/resources.tf
prometheus_all/input.tf

Related to terraform issue: https://github.com/hashicorp/terraform/issues/24142
We can't pass a null value to a module as it is passed explicitly
instead of using the default set inside of the module.
As a workaround we set empty string as default and set local variables
conditionally.
Try to use default values for grafana runtime, prometheus memory and disk

Fix variable defaults

---

grafana/dashboards/paas_billing.json

It was missing the resource type filter
Deployed here: https://grafana-teaching-vacancies.london.cloudapps.digital/d/tIw8h_G7z2/paas-billing-new?orgId=1&refresh=1h

Fix paas billing daily cost

---

alertmanager/README.md
alertmanager/config/alertmanager.yml.tmpl

By adding this route any alert tagged with the label daily will only send a message to slack once every 24 hours. this will stop regular repetitive warnings from swamping the slack channels
Add a label to your alert i.e:
```
name: DailyRoute
expr: sum(increase(cpu[1d])) > 90 and on() hour()  == 11
labels:
period: daily
severity: low
annotations:
dashboard: https://grafana-prod-get-into-teaching.london.cloudapps.digital/d/qZjcqcpGz/csp-violations?orgId=1&viewPanel=28
description: Test CSP violation.
summary: Test CSP violation.
```
In above example the monitoring only looks for an event in a certain time period, and then when it triggers it will only send an alert to slack once in that time period

Add Route so alerts only trigger every 24h

---

prometheus/input.tf
prometheus/resources.tf

Increase retention time to 12h as prometheus garbage collection period is 2h. It may avoid weird edge cases.
Now limiting disk size to 1G with the retention.size option.
Check disk size in BAT: https://grafana-bat.london.cloudapps.digital/d/eF19g4RZx/cf-apps?orgId=1&refresh=10s&var-SpaceName=bat-prod&var-Applications=prometheus-bat&from=now-24h&to=now

Change prometheus storage retention

---

prometheus/templates/prometheus.yml.tmpl

The guid label changes at each application deployment. For the same metric it creates an infinity of time series.
Now it is dropped before getting ingested by prometheus.
It's deployed to BAT QA. Check the guid label is not present: https://prometheus-readonly-bat-qa.london.cloudapps.digital/graph?g0.expr=cpu&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=6h
Even it was present in the exporter: https://paas-prometheus-exporter-bat-qa.london.cloudapps.digital/metrics

[451] Drop guid label from paas exporter metrics

---

grafana/dashboards/yabeda_sidekiq.json

**What**:
Additions/Modifications to Yabeda Sidekiq dashboard in Grafana
-updated Job Processing by Job Type graph to use _sum instead of _bucket, to improve results
-added table to RH side of Job Processing by Job Type graph
-new Job Runtime bar gauge
-new Active Processes graph
-new Active/Available Worker graph
-new CPU & Memory used by Processes graph
**How to Review**:
See new dashboard at [https://grafana-bat.london.cloudapps.digital/d/oChioth7k/yabeda-sidekiq-new?orgId=1](url)

Add new Grafana dashboard for Yabeda Sidekiq

---

README.md
paas_prometheus_exporter/output.tf
prometheus/templates/prometheus.yml.tmpl

The default instance label is not useful and it creates many useless time series because of its high cardinality. We replace it with the app instance number from Cloud foundry which is more useful.
Related to: https://github.com/DFE-Digital/apply-for-teacher-training/pull/6320
Deployed to https://prometheus-bat-qa.london.cloudapps.digital/

[452] Remove or rename instance label from prometheus metrics

---

prometheus/templates/prometheus.yml.tmpl

Fix error in prometheus relabel config: the instance label is not replaced
Deployed to https://prometheus-bat-qa.london.cloudapps.digital/

[452] Fix prometheus relabelling

---

README.md
alertmanager/input.tf
alertmanager/resources.tf
billing_prometheus_exporter/input.tf
billing_prometheus_exporter/main.tf
paas_prometheus_exporter/input.tf
paas_prometheus_exporter/resources.tf
prometheus/input.tf
prometheus/resources.tf
prometheus_all/input.tf
prometheus_all/resources.tf
redis_prometheus_exporter/input.tf
redis_prometheus_exporter/resource.tf

Adding an optional docker credential for each apps  pulling from Dockerhub. Authenticating image pulls from Dockerhub when deploying the stack will resolve pull rate limit error.
https://trello.com/c/hxRVggGN

Add docker credential

---

prometheus/templates/prometheus.yml.tmpl

The instance label should be replaced by app_instance if it is present.
It should be left untouched if app_instance is NOT present.
We now add a regex to make sure app_instance is not empty before
replacing instance.
Test with metric with instance label, with and and without app_instance

[495] Selectively replace the instance label

---

.github/workflows/release.yml

This is an attempt to version each merge to master branch as a GH Release. With this,
other consuming repo can then pin to specific version or latest release. At this moment,
we don’t have the option to do that i.e. everyone gets the latest commit, which could sometimes
cause issues in the consumping repo through terraform.

Create GH Release and Tag on merge to master

---

postgres_prometheus_exporter/input.tf
postgres_prometheus_exporter/resource.tf

A service key is created to allow the postgres_prometheus_exporter to connect to each app's postgres service.  This key is named after the app's postgres service which conflicts with a key created in the app's terraform file.  
Renamed postgres servicekey to make it clear it belongs to the postgres_prometheus_exporter
The existing service keys for `apply-postgres-qa` & `teacher-training-api-postgres-qa` will be destroyed and replaced.  The service keys created during the deployment workflows for these applications have their own suffixes.
A new service key will be created for `register-postgres-qa`.
https://trello.com/c/SfDpEYbL

Rename the postgres service key

---

grafana/dashboards/postgresql_table_row_counts.json

Add a dashboard for the PostgresQL table row_count stats that we are now collecting
https://trello.com/c/IEiInWZd/4898-track-database-table-row-counts-in-grafana
dashboard currently imported into QA and Prod

Add Dashboard for PostgreSQL table row counts

---

grafana/dashboards/yabeda_delayed_jobs.json

Add a dashboard to display metrics from the yabeda delayed jobs gem. This is a clone of the yabeda sidekiq dashboard, but with a few of the panels that don't apply removed.
We're using a [fork](https://github.com/DFE-Digital/yabeda-delayed_job) of the yabeda delayed jobs gem to ensure no PII leaks into the metrics labels.
Closes #55 - accidental fork.

Add dashboard for yabeda delayed jobs metrics

---

grafana/dashboards/cf_apps.json

The HTTP requests panel currently reports on total requests and failed requests, failed requests being defined as anything in the 4xx & 5xx ranges.
Report on the 4xx and 5xx responses separately to align with the failed requests alert.  This makes the information presented in the single app more relevant to the alert that links to it and more useful generally for understanding the source of failed requests.  However, the multi app view is harder to read due to increased amount of data displayed.
- The change can be deployed to QA using the [test-http-request-dashboard](https://github.com/DFE-Digital/bat-infrastructure/tree/test-http-request-dashboard) branch of bat-infrastructure (already deployed, may need redeploying)
- Compare the [single app …

Refine HTTP requests panel on cf apps dashboard

---

README.md
prometheus/input.tf
prometheus/resources.tf
prometheus/templates/pg_alert.rules.tmpl
prometheus_all/input.tf
prometheus_all/resources.tf

Adding Postgres alerting for memory, cpu and storage space.
Service is added to Postgres alerting by setting these variables in the calling app
(e.g. as per bat-infrastructure/monitoring)
-alertable_postgres_services
-postgres_dashboard_url
**Note that standard alerting must also be enabled**
Default settings to alert if
-Cpu usage > 60%
-Memory avail < 1GB
-Storage space avail < 1GB
https://trello.com/c/D42mz0JW/419-alerting-on-postgres-memory-cpu-limit
Config changes tested via 'make qa'

Add generic Postgres alerting

---

prometheus/input.tf

Enabled alerting on postgres services.
[x][Attached to trello](https://trello.com/c/zFypsIyI/175-prometheus-alert-app-memory-cpu)

Set alerting to deploy when there are alertable postgres services.

---

README.md
prometheus/input.tf
prometheus/templates/app_alert.rules.tmpl

Grafana dashboard url now takes to the correct space and app.
[x] [Attached to trello](https://trello.com/c/jdMCU23P/435-move-paas-app-alerting-to-cf-monitoring)

Space name included in the grafana dashboard url

---

alertmanager/README.md
alertmanager/config/alertmanager.yml.tmpl
alertmanager/input.tf
prometheus_all/input.tf
prometheus_all/resources.tf

Some teams would like alerts related to their apps routed to their own Slack channels.  Currently the alertmanager template only supports sending alerts to a single incoming Slack webhook.
- An optional input accepts a map of alertmanager routes\receivers along with Slack webhooks that are associated with the receivers.  
- Additional routes\receivers defined in the alertmanager template.  Each route is allocated a matcher of the same name so that alerts can be routed to it.
- Messages sent to the default route will have a footer appended to them displaying "Sent to default route"
- Confirm that the changes are optional (ie they won't break existing templates that call this module but haven't opted in to the change)

Add additional, optional Slack receivers

---

README.md
grafana/config/grafana.ini
grafana/input.tf
prometheus_all/input.tf
prometheus_all/resources.tf

Add a variable to enable anonymous readonly access to the Grafana dashboards and metrics. This is useful to be able to present on logged out TV screens.
Sign out and access https://grafana-bat-qa.london.cloudapps.digital/

[592] Grafana anonymous authentication
